// source: buildsafe/v1/search.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.buildsafe.v1.Cvss');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.buildsafe.v1.Cvss3Metrics');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.buildsafe.v1.Cvss = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.buildsafe.v1.Cvss, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.buildsafe.v1.Cvss.displayName = 'proto.buildsafe.v1.Cvss';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.buildsafe.v1.Cvss.prototype.toObject = function(opt_includeInstance) {
  return proto.buildsafe.v1.Cvss.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.buildsafe.v1.Cvss} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.buildsafe.v1.Cvss.toObject = function(includeInstance, msg) {
  var f, obj = {
    vector: jspb.Message.getFieldWithDefault(msg, 1, ""),
    version: jspb.Message.getFieldWithDefault(msg, 2, ""),
    source: jspb.Message.getFieldWithDefault(msg, 3, ""),
    type: jspb.Message.getFieldWithDefault(msg, 4, ""),
    metrics: (f = msg.getMetrics()) && proto.buildsafe.v1.Cvss3Metrics.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.buildsafe.v1.Cvss}
 */
proto.buildsafe.v1.Cvss.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.buildsafe.v1.Cvss;
  return proto.buildsafe.v1.Cvss.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.buildsafe.v1.Cvss} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.buildsafe.v1.Cvss}
 */
proto.buildsafe.v1.Cvss.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setVector(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSource(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 5:
      var value = new proto.buildsafe.v1.Cvss3Metrics;
      reader.readMessage(value,proto.buildsafe.v1.Cvss3Metrics.deserializeBinaryFromReader);
      msg.setMetrics(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.buildsafe.v1.Cvss.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.buildsafe.v1.Cvss.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.buildsafe.v1.Cvss} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.buildsafe.v1.Cvss.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVector();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSource();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMetrics();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.buildsafe.v1.Cvss3Metrics.serializeBinaryToWriter
    );
  }
};


/**
 * optional string vector = 1;
 * @return {string}
 */
proto.buildsafe.v1.Cvss.prototype.getVector = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.buildsafe.v1.Cvss} returns this
 */
proto.buildsafe.v1.Cvss.prototype.setVector = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string version = 2;
 * @return {string}
 */
proto.buildsafe.v1.Cvss.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.buildsafe.v1.Cvss} returns this
 */
proto.buildsafe.v1.Cvss.prototype.setVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string source = 3;
 * @return {string}
 */
proto.buildsafe.v1.Cvss.prototype.getSource = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.buildsafe.v1.Cvss} returns this
 */
proto.buildsafe.v1.Cvss.prototype.setSource = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string type = 4;
 * @return {string}
 */
proto.buildsafe.v1.Cvss.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.buildsafe.v1.Cvss} returns this
 */
proto.buildsafe.v1.Cvss.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional Cvss3Metrics metrics = 5;
 * @return {?proto.buildsafe.v1.Cvss3Metrics}
 */
proto.buildsafe.v1.Cvss.prototype.getMetrics = function() {
  return /** @type{?proto.buildsafe.v1.Cvss3Metrics} */ (
    jspb.Message.getWrapperField(this, proto.buildsafe.v1.Cvss3Metrics, 5));
};


/**
 * @param {?proto.buildsafe.v1.Cvss3Metrics|undefined} value
 * @return {!proto.buildsafe.v1.Cvss} returns this
*/
proto.buildsafe.v1.Cvss.prototype.setMetrics = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.buildsafe.v1.Cvss} returns this
 */
proto.buildsafe.v1.Cvss.prototype.clearMetrics = function() {
  return this.setMetrics(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.buildsafe.v1.Cvss.prototype.hasMetrics = function() {
  return jspb.Message.getField(this, 5) != null;
};


