// source: buildsafe/v1/search.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.buildsafe.v1.Package');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.buildsafe.v1.Package = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.buildsafe.v1.Package.repeatedFields_, null);
};
goog.inherits(proto.buildsafe.v1.Package, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.buildsafe.v1.Package.displayName = 'proto.buildsafe.v1.Package';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.buildsafe.v1.Package.repeatedFields_ = [9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.buildsafe.v1.Package.prototype.toObject = function(opt_includeInstance) {
  return proto.buildsafe.v1.Package.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.buildsafe.v1.Package} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.buildsafe.v1.Package.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    revision: jspb.Message.getFieldWithDefault(msg, 2, ""),
    version: jspb.Message.getFieldWithDefault(msg, 3, ""),
    description: jspb.Message.getFieldWithDefault(msg, 4, ""),
    homepage: jspb.Message.getFieldWithDefault(msg, 5, ""),
    free: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    spdxId: jspb.Message.getFieldWithDefault(msg, 7, ""),
    epochSeconds: jspb.Message.getFieldWithDefault(msg, 8, 0),
    platformsList: (f = jspb.Message.getRepeatedField(msg, 9)) == null ? undefined : f,
    cpe: jspb.Message.getFieldWithDefault(msg, 10, ""),
    attrName: jspb.Message.getFieldWithDefault(msg, 11, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.buildsafe.v1.Package}
 */
proto.buildsafe.v1.Package.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.buildsafe.v1.Package;
  return proto.buildsafe.v1.Package.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.buildsafe.v1.Package} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.buildsafe.v1.Package}
 */
proto.buildsafe.v1.Package.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRevision(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setHomepage(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setFree(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setSpdxId(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setEpochSeconds(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.addPlatforms(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setCpe(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setAttrName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.buildsafe.v1.Package.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.buildsafe.v1.Package.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.buildsafe.v1.Package} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.buildsafe.v1.Package.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRevision();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getHomepage();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getFree();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getSpdxId();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getEpochSeconds();
  if (f !== 0) {
    writer.writeUint64(
      8,
      f
    );
  }
  f = message.getPlatformsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      9,
      f
    );
  }
  f = message.getCpe();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getAttrName();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.buildsafe.v1.Package.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.buildsafe.v1.Package} returns this
 */
proto.buildsafe.v1.Package.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string revision = 2;
 * @return {string}
 */
proto.buildsafe.v1.Package.prototype.getRevision = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.buildsafe.v1.Package} returns this
 */
proto.buildsafe.v1.Package.prototype.setRevision = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string version = 3;
 * @return {string}
 */
proto.buildsafe.v1.Package.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.buildsafe.v1.Package} returns this
 */
proto.buildsafe.v1.Package.prototype.setVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string description = 4;
 * @return {string}
 */
proto.buildsafe.v1.Package.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.buildsafe.v1.Package} returns this
 */
proto.buildsafe.v1.Package.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string homepage = 5;
 * @return {string}
 */
proto.buildsafe.v1.Package.prototype.getHomepage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.buildsafe.v1.Package} returns this
 */
proto.buildsafe.v1.Package.prototype.setHomepage = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional bool free = 6;
 * @return {boolean}
 */
proto.buildsafe.v1.Package.prototype.getFree = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.buildsafe.v1.Package} returns this
 */
proto.buildsafe.v1.Package.prototype.setFree = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional string spdx_id = 7;
 * @return {string}
 */
proto.buildsafe.v1.Package.prototype.getSpdxId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.buildsafe.v1.Package} returns this
 */
proto.buildsafe.v1.Package.prototype.setSpdxId = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional uint64 epoch_seconds = 8;
 * @return {number}
 */
proto.buildsafe.v1.Package.prototype.getEpochSeconds = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.buildsafe.v1.Package} returns this
 */
proto.buildsafe.v1.Package.prototype.setEpochSeconds = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * repeated string platforms = 9;
 * @return {!Array<string>}
 */
proto.buildsafe.v1.Package.prototype.getPlatformsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 9));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.buildsafe.v1.Package} returns this
 */
proto.buildsafe.v1.Package.prototype.setPlatformsList = function(value) {
  return jspb.Message.setField(this, 9, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.buildsafe.v1.Package} returns this
 */
proto.buildsafe.v1.Package.prototype.addPlatforms = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 9, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.buildsafe.v1.Package} returns this
 */
proto.buildsafe.v1.Package.prototype.clearPlatformsList = function() {
  return this.setPlatformsList([]);
};


/**
 * optional string cpe = 10;
 * @return {string}
 */
proto.buildsafe.v1.Package.prototype.getCpe = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.buildsafe.v1.Package} returns this
 */
proto.buildsafe.v1.Package.prototype.setCpe = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string attr_name = 11;
 * @return {string}
 */
proto.buildsafe.v1.Package.prototype.getAttrName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.buildsafe.v1.Package} returns this
 */
proto.buildsafe.v1.Package.prototype.setAttrName = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


