schema = 3

[mod]
  [mod."buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go"]
    version = "v1.35.1-20240920164238-5a7b106cbb87.1"
    hash = "sha256-sBq9i5q58Bo1BFzrCIgAD+LdtYkWgmIH7zZs0hQJOkI="
  [mod."github.com/grpc-ecosystem/grpc-gateway/v2"]
    version = "v2.23.0"
    hash = "sha256-c8pgJanNawMpiCXAevKk5KVynzD/vYWTBt+ktznUQ5c="
  [mod."golang.org/x/net"]
    version = "v0.30.0"
    hash = "sha256-i1f6wJHfFq0nKtbuY7twZ7uPyUbRYHVjd3uy0SS06mU="
  [mod."golang.org/x/sys"]
    version = "v0.26.0"
    hash = "sha256-YjklsWNhx4g4TaWRWfFe1TMFKujbqiaNvZ38bfI35fM="
  [mod."golang.org/x/text"]
    version = "v0.19.0"
    hash = "sha256-C92pSYLLUQ2NKKcc60wpoSJ5UWAfnWkmd997C13fXdU="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20241104194629-dd2ea8efbc28"
    hash = "sha256-bzgzq8kyliyaWXIIGN1zztXCvZl4NHcUHdGXufRFtRE="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20241104194629-dd2ea8efbc28"
    hash = "sha256-Fk+cG5bRI3BvnqhWzvMzbU36cC7PM+o2oAOJmvVx9M0="
  [mod."google.golang.org/grpc"]
    version = "v1.67.1"
    hash = "sha256-VqfKp80c2B1MK4m1WtHW4r7ykqdChJbqaMn+gMEYmYc="
  [mod."google.golang.org/protobuf"]
    version = "v1.35.1"
    hash = "sha256-4NtUQoBvlPGFGjo7c+E1EBS/sb8oy50MGy45KGWPpWo="
