schema = 3

[mod]
  [mod."buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go"]
    version = "v1.32.0-20231115204500-e097f827e652.1"
    hash = "sha256-z+s4I7K/QKi/I2gUxc0u0Y/DQG6GZC4Yg/snFw3Ahyk="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.3"
    hash = "sha256-svogITcP4orUIsJFjMtp+Uv1+fKJv2Q5Zwf2dMqnpOQ="
  [mod."github.com/grpc-ecosystem/grpc-gateway/v2"]
    version = "v2.19.1"
    hash = "sha256-rCFj39yIjx/xX99OSAncloxaJP1IJG59fK2CwU5M2WY="
  [mod."golang.org/x/net"]
    version = "v0.20.0"
    hash = "sha256-PCttIsWSBQd6fDXL49jepszUAMLnAGAKR//5EDO3XDk="
  [mod."golang.org/x/sys"]
    version = "v0.16.0"
    hash = "sha256-ZkGclbp2S7NQYhbuGji6XokCn2Qi1BJy8dwyAOTV8sY="
  [mod."golang.org/x/text"]
    version = "v0.14.0"
    hash = "sha256-yh3B0tom1RfzQBf1RNmfdNWF1PtiqxV41jW1GVS6JAg="
  [mod."google.golang.org/genproto"]
    version = "v0.0.0-20240116215550-a9fa1716bcac"
    hash = "sha256-5hedgpx2PWiNr216vF6KRADPqyU68l3QzKfnMyxIovY="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20240125205218-1f4bbc51befe"
    hash = "sha256-m1wAOo4INg46fIrGdISN5m5X29Z6OdR151xdKqrD9V4="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20240125205218-1f4bbc51befe"
    hash = "sha256-b22XLgjrH5i0wUw4iseepgLzjOpFgixWHfGPgl11kbo="
  [mod."google.golang.org/grpc"]
    version = "v1.61.0"
    hash = "sha256-+LvlQyeIaM0GgOQoa3rVmM9OS0UtbdK54Fvl3dgJEt8="
  [mod."google.golang.org/protobuf"]
    version = "v1.32.0"
    hash = "sha256-GJuTkMGHCzHbyK4yD5kY4oMn8wQWqgkeBK//yVDqHJk="
