/**
 * @fileoverview gRPC-Web generated client stub for buildsafe.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: buildsafe/v1/app.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var buf_validate_validate_pb = require('../../buf/validate/validate_pb.js')

var google_api_annotations_pb = require('../../google/api/annotations_pb.js')
const proto = {};
proto.buildsafe = {};
proto.buildsafe.v1 = require('./app_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.buildsafe.v1.AppServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.buildsafe.v1.AppServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.buildsafe.v1.RegisterAppRequest,
 *   !proto.buildsafe.v1.RegisterAppResponse>}
 */
const methodDescriptor_AppService_RegisterApp = new grpc.web.MethodDescriptor(
  '/buildsafe.v1.AppService/RegisterApp',
  grpc.web.MethodType.UNARY,
  proto.buildsafe.v1.RegisterAppRequest,
  proto.buildsafe.v1.RegisterAppResponse,
  /**
   * @param {!proto.buildsafe.v1.RegisterAppRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.buildsafe.v1.RegisterAppResponse.deserializeBinary
);


/**
 * @param {!proto.buildsafe.v1.RegisterAppRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.buildsafe.v1.RegisterAppResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.buildsafe.v1.RegisterAppResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.buildsafe.v1.AppServiceClient.prototype.registerApp =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/buildsafe.v1.AppService/RegisterApp',
      request,
      metadata || {},
      methodDescriptor_AppService_RegisterApp,
      callback);
};


/**
 * @param {!proto.buildsafe.v1.RegisterAppRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.buildsafe.v1.RegisterAppResponse>}
 *     Promise that resolves to the response
 */
proto.buildsafe.v1.AppServicePromiseClient.prototype.registerApp =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/buildsafe.v1.AppService/RegisterApp',
      request,
      metadata || {},
      methodDescriptor_AppService_RegisterApp);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.buildsafe.v1.GetAppRequest,
 *   !proto.buildsafe.v1.GetAppResponse>}
 */
const methodDescriptor_AppService_GetApp = new grpc.web.MethodDescriptor(
  '/buildsafe.v1.AppService/GetApp',
  grpc.web.MethodType.UNARY,
  proto.buildsafe.v1.GetAppRequest,
  proto.buildsafe.v1.GetAppResponse,
  /**
   * @param {!proto.buildsafe.v1.GetAppRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.buildsafe.v1.GetAppResponse.deserializeBinary
);


/**
 * @param {!proto.buildsafe.v1.GetAppRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.buildsafe.v1.GetAppResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.buildsafe.v1.GetAppResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.buildsafe.v1.AppServiceClient.prototype.getApp =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/buildsafe.v1.AppService/GetApp',
      request,
      metadata || {},
      methodDescriptor_AppService_GetApp,
      callback);
};


/**
 * @param {!proto.buildsafe.v1.GetAppRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.buildsafe.v1.GetAppResponse>}
 *     Promise that resolves to the response
 */
proto.buildsafe.v1.AppServicePromiseClient.prototype.getApp =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/buildsafe.v1.AppService/GetApp',
      request,
      metadata || {},
      methodDescriptor_AppService_GetApp);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.buildsafe.v1.ListAppsRequest,
 *   !proto.buildsafe.v1.ListAppsResponse>}
 */
const methodDescriptor_AppService_ListApps = new grpc.web.MethodDescriptor(
  '/buildsafe.v1.AppService/ListApps',
  grpc.web.MethodType.UNARY,
  proto.buildsafe.v1.ListAppsRequest,
  proto.buildsafe.v1.ListAppsResponse,
  /**
   * @param {!proto.buildsafe.v1.ListAppsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.buildsafe.v1.ListAppsResponse.deserializeBinary
);


/**
 * @param {!proto.buildsafe.v1.ListAppsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.buildsafe.v1.ListAppsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.buildsafe.v1.ListAppsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.buildsafe.v1.AppServiceClient.prototype.listApps =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/buildsafe.v1.AppService/ListApps',
      request,
      metadata || {},
      methodDescriptor_AppService_ListApps,
      callback);
};


/**
 * @param {!proto.buildsafe.v1.ListAppsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.buildsafe.v1.ListAppsResponse>}
 *     Promise that resolves to the response
 */
proto.buildsafe.v1.AppServicePromiseClient.prototype.listApps =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/buildsafe.v1.AppService/ListApps',
      request,
      metadata || {},
      methodDescriptor_AppService_ListApps);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.buildsafe.v1.UnregisterAppRequest,
 *   !proto.buildsafe.v1.UnregisterAppResponse>}
 */
const methodDescriptor_AppService_UnregisterApp = new grpc.web.MethodDescriptor(
  '/buildsafe.v1.AppService/UnregisterApp',
  grpc.web.MethodType.UNARY,
  proto.buildsafe.v1.UnregisterAppRequest,
  proto.buildsafe.v1.UnregisterAppResponse,
  /**
   * @param {!proto.buildsafe.v1.UnregisterAppRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.buildsafe.v1.UnregisterAppResponse.deserializeBinary
);


/**
 * @param {!proto.buildsafe.v1.UnregisterAppRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.buildsafe.v1.UnregisterAppResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.buildsafe.v1.UnregisterAppResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.buildsafe.v1.AppServiceClient.prototype.unregisterApp =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/buildsafe.v1.AppService/UnregisterApp',
      request,
      metadata || {},
      methodDescriptor_AppService_UnregisterApp,
      callback);
};


/**
 * @param {!proto.buildsafe.v1.UnregisterAppRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.buildsafe.v1.UnregisterAppResponse>}
 *     Promise that resolves to the response
 */
proto.buildsafe.v1.AppServicePromiseClient.prototype.unregisterApp =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/buildsafe.v1.AppService/UnregisterApp',
      request,
      metadata || {},
      methodDescriptor_AppService_UnregisterApp);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.buildsafe.v1.AddAppDetailsRequest,
 *   !proto.buildsafe.v1.AddAppDetailsResponse>}
 */
const methodDescriptor_AppService_AddAppDetails = new grpc.web.MethodDescriptor(
  '/buildsafe.v1.AppService/AddAppDetails',
  grpc.web.MethodType.UNARY,
  proto.buildsafe.v1.AddAppDetailsRequest,
  proto.buildsafe.v1.AddAppDetailsResponse,
  /**
   * @param {!proto.buildsafe.v1.AddAppDetailsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.buildsafe.v1.AddAppDetailsResponse.deserializeBinary
);


/**
 * @param {!proto.buildsafe.v1.AddAppDetailsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.buildsafe.v1.AddAppDetailsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.buildsafe.v1.AddAppDetailsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.buildsafe.v1.AppServiceClient.prototype.addAppDetails =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/buildsafe.v1.AppService/AddAppDetails',
      request,
      metadata || {},
      methodDescriptor_AppService_AddAppDetails,
      callback);
};


/**
 * @param {!proto.buildsafe.v1.AddAppDetailsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.buildsafe.v1.AddAppDetailsResponse>}
 *     Promise that resolves to the response
 */
proto.buildsafe.v1.AppServicePromiseClient.prototype.addAppDetails =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/buildsafe.v1.AppService/AddAppDetails',
      request,
      metadata || {},
      methodDescriptor_AppService_AddAppDetails);
};


module.exports = proto.buildsafe.v1;

