/**
 * @fileoverview gRPC-Web generated client stub for buildsafe.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: buildsafe/v1/auth.proto


/* eslint-disable */
// @ts-nocheck


goog.provide('proto.buildsafe.v1.AuthServiceClient');
goog.provide('proto.buildsafe.v1.AuthServicePromiseClient');

goog.require('grpc.web.MethodDescriptor');
goog.require('grpc.web.MethodType');
goog.require('grpc.web.GrpcWebClientBase');
goog.require('grpc.web.AbstractClientBase');
goog.require('grpc.web.ClientReadableStream');
goog.require('grpc.web.RpcError');
goog.require('proto.buildsafe.v1.OAuthAuthenticateRequest');
goog.require('proto.buildsafe.v1.OAuthAuthenticateResponse');

goog.requireType('grpc.web.ClientOptions');



goog.scope(function() {

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.buildsafe.v1.AuthServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.buildsafe.v1.AuthServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.buildsafe.v1.OAuthAuthenticateRequest,
 *   !proto.buildsafe.v1.OAuthAuthenticateResponse>}
 */
const methodDescriptor_AuthService_OAuthAuthenticate = new grpc.web.MethodDescriptor(
  '/buildsafe.v1.AuthService/OAuthAuthenticate',
  grpc.web.MethodType.UNARY,
  proto.buildsafe.v1.OAuthAuthenticateRequest,
  proto.buildsafe.v1.OAuthAuthenticateResponse,
  /**
   * @param {!proto.buildsafe.v1.OAuthAuthenticateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.buildsafe.v1.OAuthAuthenticateResponse.deserializeBinary
);


/**
 * @param {!proto.buildsafe.v1.OAuthAuthenticateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.buildsafe.v1.OAuthAuthenticateResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.buildsafe.v1.OAuthAuthenticateResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.buildsafe.v1.AuthServiceClient.prototype.oAuthAuthenticate =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/buildsafe.v1.AuthService/OAuthAuthenticate',
      request,
      metadata || {},
      methodDescriptor_AuthService_OAuthAuthenticate,
      callback);
};


/**
 * @param {!proto.buildsafe.v1.OAuthAuthenticateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.buildsafe.v1.OAuthAuthenticateResponse>}
 *     Promise that resolves to the response
 */
proto.buildsafe.v1.AuthServicePromiseClient.prototype.oAuthAuthenticate =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/buildsafe.v1.AuthService/OAuthAuthenticate',
      request,
      metadata || {},
      methodDescriptor_AuthService_OAuthAuthenticate);
};


}); // goog.scope

