/**
 * @fileoverview gRPC-Web generated client stub for buildsafe.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: buildsafe/v1/search.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var buf_validate_validate_pb = require('../../buf/validate/validate_pb.js')

var google_api_annotations_pb = require('../../google/api/annotations_pb.js')
const proto = {};
proto.buildsafe = {};
proto.buildsafe.v1 = require('./search_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.buildsafe.v1.SearchServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.buildsafe.v1.SearchServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.buildsafe.v1.ListPackagesRequest,
 *   !proto.buildsafe.v1.ListPackagesResponse>}
 */
const methodDescriptor_SearchService_ListPackages = new grpc.web.MethodDescriptor(
  '/buildsafe.v1.SearchService/ListPackages',
  grpc.web.MethodType.UNARY,
  proto.buildsafe.v1.ListPackagesRequest,
  proto.buildsafe.v1.ListPackagesResponse,
  /**
   * @param {!proto.buildsafe.v1.ListPackagesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.buildsafe.v1.ListPackagesResponse.deserializeBinary
);


/**
 * @param {!proto.buildsafe.v1.ListPackagesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.buildsafe.v1.ListPackagesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.buildsafe.v1.ListPackagesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.buildsafe.v1.SearchServiceClient.prototype.listPackages =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/buildsafe.v1.SearchService/ListPackages',
      request,
      metadata || {},
      methodDescriptor_SearchService_ListPackages,
      callback);
};


/**
 * @param {!proto.buildsafe.v1.ListPackagesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.buildsafe.v1.ListPackagesResponse>}
 *     Promise that resolves to the response
 */
proto.buildsafe.v1.SearchServicePromiseClient.prototype.listPackages =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/buildsafe.v1.SearchService/ListPackages',
      request,
      metadata || {},
      methodDescriptor_SearchService_ListPackages);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.buildsafe.v1.FetchPackagesRequest,
 *   !proto.buildsafe.v1.FetchPackagesResponse>}
 */
const methodDescriptor_SearchService_FetchPackages = new grpc.web.MethodDescriptor(
  '/buildsafe.v1.SearchService/FetchPackages',
  grpc.web.MethodType.UNARY,
  proto.buildsafe.v1.FetchPackagesRequest,
  proto.buildsafe.v1.FetchPackagesResponse,
  /**
   * @param {!proto.buildsafe.v1.FetchPackagesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.buildsafe.v1.FetchPackagesResponse.deserializeBinary
);


/**
 * @param {!proto.buildsafe.v1.FetchPackagesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.buildsafe.v1.FetchPackagesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.buildsafe.v1.FetchPackagesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.buildsafe.v1.SearchServiceClient.prototype.fetchPackages =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/buildsafe.v1.SearchService/FetchPackages',
      request,
      metadata || {},
      methodDescriptor_SearchService_FetchPackages,
      callback);
};


/**
 * @param {!proto.buildsafe.v1.FetchPackagesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.buildsafe.v1.FetchPackagesResponse>}
 *     Promise that resolves to the response
 */
proto.buildsafe.v1.SearchServicePromiseClient.prototype.fetchPackages =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/buildsafe.v1.SearchService/FetchPackages',
      request,
      metadata || {},
      methodDescriptor_SearchService_FetchPackages);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.buildsafe.v1.FetchPackageVersionRequest,
 *   !proto.buildsafe.v1.FetchPackageVersionResponse>}
 */
const methodDescriptor_SearchService_FetchPackageVersion = new grpc.web.MethodDescriptor(
  '/buildsafe.v1.SearchService/FetchPackageVersion',
  grpc.web.MethodType.UNARY,
  proto.buildsafe.v1.FetchPackageVersionRequest,
  proto.buildsafe.v1.FetchPackageVersionResponse,
  /**
   * @param {!proto.buildsafe.v1.FetchPackageVersionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.buildsafe.v1.FetchPackageVersionResponse.deserializeBinary
);


/**
 * @param {!proto.buildsafe.v1.FetchPackageVersionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.buildsafe.v1.FetchPackageVersionResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.buildsafe.v1.FetchPackageVersionResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.buildsafe.v1.SearchServiceClient.prototype.fetchPackageVersion =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/buildsafe.v1.SearchService/FetchPackageVersion',
      request,
      metadata || {},
      methodDescriptor_SearchService_FetchPackageVersion,
      callback);
};


/**
 * @param {!proto.buildsafe.v1.FetchPackageVersionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.buildsafe.v1.FetchPackageVersionResponse>}
 *     Promise that resolves to the response
 */
proto.buildsafe.v1.SearchServicePromiseClient.prototype.fetchPackageVersion =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/buildsafe.v1.SearchService/FetchPackageVersion',
      request,
      metadata || {},
      methodDescriptor_SearchService_FetchPackageVersion);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.buildsafe.v1.FetchVulnerabilitiesRequest,
 *   !proto.buildsafe.v1.FetchVulnerabilitiesResponse>}
 */
const methodDescriptor_SearchService_FetchVulnerabilities = new grpc.web.MethodDescriptor(
  '/buildsafe.v1.SearchService/FetchVulnerabilities',
  grpc.web.MethodType.UNARY,
  proto.buildsafe.v1.FetchVulnerabilitiesRequest,
  proto.buildsafe.v1.FetchVulnerabilitiesResponse,
  /**
   * @param {!proto.buildsafe.v1.FetchVulnerabilitiesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.buildsafe.v1.FetchVulnerabilitiesResponse.deserializeBinary
);


/**
 * @param {!proto.buildsafe.v1.FetchVulnerabilitiesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.buildsafe.v1.FetchVulnerabilitiesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.buildsafe.v1.FetchVulnerabilitiesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.buildsafe.v1.SearchServiceClient.prototype.fetchVulnerabilities =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/buildsafe.v1.SearchService/FetchVulnerabilities',
      request,
      metadata || {},
      methodDescriptor_SearchService_FetchVulnerabilities,
      callback);
};


/**
 * @param {!proto.buildsafe.v1.FetchVulnerabilitiesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.buildsafe.v1.FetchVulnerabilitiesResponse>}
 *     Promise that resolves to the response
 */
proto.buildsafe.v1.SearchServicePromiseClient.prototype.fetchVulnerabilities =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/buildsafe.v1.SearchService/FetchVulnerabilities',
      request,
      metadata || {},
      methodDescriptor_SearchService_FetchVulnerabilities);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.buildsafe.v1.FetchMaintainersInfoRequest,
 *   !proto.buildsafe.v1.Maintainer>}
 */
const methodDescriptor_SearchService_FetchMaintainersInfo = new grpc.web.MethodDescriptor(
  '/buildsafe.v1.SearchService/FetchMaintainersInfo',
  grpc.web.MethodType.UNARY,
  proto.buildsafe.v1.FetchMaintainersInfoRequest,
  proto.buildsafe.v1.Maintainer,
  /**
   * @param {!proto.buildsafe.v1.FetchMaintainersInfoRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.buildsafe.v1.Maintainer.deserializeBinary
);


/**
 * @param {!proto.buildsafe.v1.FetchMaintainersInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.buildsafe.v1.Maintainer)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.buildsafe.v1.Maintainer>|undefined}
 *     The XHR Node Readable Stream
 */
proto.buildsafe.v1.SearchServiceClient.prototype.fetchMaintainersInfo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/buildsafe.v1.SearchService/FetchMaintainersInfo',
      request,
      metadata || {},
      methodDescriptor_SearchService_FetchMaintainersInfo,
      callback);
};


/**
 * @param {!proto.buildsafe.v1.FetchMaintainersInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.buildsafe.v1.Maintainer>}
 *     Promise that resolves to the response
 */
proto.buildsafe.v1.SearchServicePromiseClient.prototype.fetchMaintainersInfo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/buildsafe.v1.SearchService/FetchMaintainersInfo',
      request,
      metadata || {},
      methodDescriptor_SearchService_FetchMaintainersInfo);
};


module.exports = proto.buildsafe.v1;

