// (-- api-linter: core::0191::java-package=disabled
// (-- api-linter: core::0191::java-outer-classname=disabled
// (-- api-linter: core::0191::java-multiple-files=disabled
//     aip.dev/not-precedent: We're doing This as this is a Go server --)
// (-- api-linter: core::0191::proto-package=disabled

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: buildsafe/v1/quota.proto

package bsfv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ViewQuotaRequest is the request message for viewing Quota on ViewQuota.
type ViewQuotaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId int64 `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
}

func (x *ViewQuotaRequest) Reset() {
	*x = ViewQuotaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buildsafe_v1_quota_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewQuotaRequest) ProtoMessage() {}

func (x *ViewQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buildsafe_v1_quota_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewQuotaRequest.ProtoReflect.Descriptor instead.
func (*ViewQuotaRequest) Descriptor() ([]byte, []int) {
	return file_buildsafe_v1_quota_proto_rawDescGZIP(), []int{0}
}

func (x *ViewQuotaRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

// ViewQuotaResponse  is a message for the response of ViewQuota.
type ViewQuotaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PullRequestsCount int64 `protobuf:"varint,1,opt,name=pull_requests_count,json=pullRequestsCount,proto3" json:"pull_requests_count,omitempty"`
	PullRequestsLimit int64 `protobuf:"varint,2,opt,name=pull_requests_limit,json=pullRequestsLimit,proto3" json:"pull_requests_limit,omitempty"`
}

func (x *ViewQuotaResponse) Reset() {
	*x = ViewQuotaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buildsafe_v1_quota_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewQuotaResponse) ProtoMessage() {}

func (x *ViewQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buildsafe_v1_quota_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewQuotaResponse.ProtoReflect.Descriptor instead.
func (*ViewQuotaResponse) Descriptor() ([]byte, []int) {
	return file_buildsafe_v1_quota_proto_rawDescGZIP(), []int{1}
}

func (x *ViewQuotaResponse) GetPullRequestsCount() int64 {
	if x != nil {
		return x.PullRequestsCount
	}
	return 0
}

func (x *ViewQuotaResponse) GetPullRequestsLimit() int64 {
	if x != nil {
		return x.PullRequestsLimit
	}
	return 0
}

var File_buildsafe_v1_quota_proto protoreflect.FileDescriptor

var file_buildsafe_v1_quota_proto_rawDesc = []byte{
	0x0a, 0x18, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x73, 0x61, 0x66, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x71,
	0x75, 0x6f, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x62, 0x75, 0x69, 0x6c,
	0x64, 0x73, 0x61, 0x66, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x62, 0x75, 0x66, 0x2f, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x10, 0x56, 0x69, 0x65, 0x77, 0x51, 0x75, 0x6f, 0x74, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x22, 0x73, 0x0a, 0x11, 0x56, 0x69, 0x65, 0x77, 0x51, 0x75,
	0x6f, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x70,
	0x75, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x70, 0x75, 0x6c, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x70,
	0x75, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x5f, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x70, 0x75, 0x6c, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x32, 0x8e, 0x01, 0x0a, 0x0c,
	0x51, 0x75, 0x6f, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x7e, 0x0a, 0x09,
	0x56, 0x69, 0x65, 0x77, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x12, 0x1e, 0x2e, 0x62, 0x75, 0x69, 0x6c,
	0x64, 0x73, 0x61, 0x66, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x51, 0x75, 0x6f,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x62, 0x75, 0x69, 0x6c,
	0x64, 0x73, 0x61, 0x66, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x51, 0x75, 0x6f,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x30, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x2a, 0x3a, 0x01, 0x2a, 0x22, 0x25, 0x2f, 0x76, 0x31, 0x2f, 0x71, 0x75, 0x6f, 0x74, 0x61,
	0x73, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2f, 0x7b, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x7d, 0x2f, 0x76, 0x69, 0x65, 0x77, 0x42, 0x28, 0x5a, 0x26,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x73, 0x61, 0x66, 0x65, 0x64, 0x65, 0x76, 0x2f, 0x62, 0x73, 0x66, 0x2d, 0x61, 0x70, 0x69, 0x73,
	0x3b, 0x62, 0x73, 0x66, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_buildsafe_v1_quota_proto_rawDescOnce sync.Once
	file_buildsafe_v1_quota_proto_rawDescData = file_buildsafe_v1_quota_proto_rawDesc
)

func file_buildsafe_v1_quota_proto_rawDescGZIP() []byte {
	file_buildsafe_v1_quota_proto_rawDescOnce.Do(func() {
		file_buildsafe_v1_quota_proto_rawDescData = protoimpl.X.CompressGZIP(file_buildsafe_v1_quota_proto_rawDescData)
	})
	return file_buildsafe_v1_quota_proto_rawDescData
}

var file_buildsafe_v1_quota_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_buildsafe_v1_quota_proto_goTypes = []interface{}{
	(*ViewQuotaRequest)(nil),  // 0: buildsafe.v1.ViewQuotaRequest
	(*ViewQuotaResponse)(nil), // 1: buildsafe.v1.ViewQuotaResponse
}
var file_buildsafe_v1_quota_proto_depIdxs = []int32{
	0, // 0: buildsafe.v1.QuotaService.ViewQuota:input_type -> buildsafe.v1.ViewQuotaRequest
	1, // 1: buildsafe.v1.QuotaService.ViewQuota:output_type -> buildsafe.v1.ViewQuotaResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_buildsafe_v1_quota_proto_init() }
func file_buildsafe_v1_quota_proto_init() {
	if File_buildsafe_v1_quota_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_buildsafe_v1_quota_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewQuotaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buildsafe_v1_quota_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewQuotaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_buildsafe_v1_quota_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_buildsafe_v1_quota_proto_goTypes,
		DependencyIndexes: file_buildsafe_v1_quota_proto_depIdxs,
		MessageInfos:      file_buildsafe_v1_quota_proto_msgTypes,
	}.Build()
	File_buildsafe_v1_quota_proto = out.File
	file_buildsafe_v1_quota_proto_rawDesc = nil
	file_buildsafe_v1_quota_proto_goTypes = nil
	file_buildsafe_v1_quota_proto_depIdxs = nil
}
