// (-- api-linter: core::0191::java-package=disabled
// (-- api-linter: core::0191::java-outer-classname=disabled
// (-- api-linter: core::0191::java-multiple-files=disabled
//     aip.dev/not-precedent: We're doing This as this is a Go server --)
// (-- api-linter: core::0191::proto-package=disabled

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: buildsafe/v1/search.proto

package bsfv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SearchService_ListPackages_FullMethodName         = "/buildsafe.v1.SearchService/ListPackages"
	SearchService_FetchPackages_FullMethodName        = "/buildsafe.v1.SearchService/FetchPackages"
	SearchService_FetchPackageVersion_FullMethodName  = "/buildsafe.v1.SearchService/FetchPackageVersion"
	SearchService_FetchVulnerabilities_FullMethodName = "/buildsafe.v1.SearchService/FetchVulnerabilities"
)

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SearchService defines the methods for searching packages
type SearchServiceClient interface {
	// ListPackages returns a list of packages available. Mostly meant for browsing if a package is available or not
	ListPackages(ctx context.Context, in *ListPackagesRequest, opts ...grpc.CallOption) (*ListPackagesResponse, error)
	// FetchPackage returns a package based on the name
	FetchPackages(ctx context.Context, in *FetchPackagesRequest, opts ...grpc.CallOption) (*FetchPackagesResponse, error)
	// FetchPackageVersion returns a package based on the name and version
	FetchPackageVersion(ctx context.Context, in *FetchPackageVersionRequest, opts ...grpc.CallOption) (*FetchPackageVersionResponse, error)
	// FetchVulnerabilities returns a list of vulnerabilities for a package based on the name and version
	FetchVulnerabilities(ctx context.Context, in *FetchVulnerabilitiesRequest, opts ...grpc.CallOption) (*FetchVulnerabilitiesResponse, error)
}

type searchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchServiceClient(cc grpc.ClientConnInterface) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) ListPackages(ctx context.Context, in *ListPackagesRequest, opts ...grpc.CallOption) (*ListPackagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPackagesResponse)
	err := c.cc.Invoke(ctx, SearchService_ListPackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) FetchPackages(ctx context.Context, in *FetchPackagesRequest, opts ...grpc.CallOption) (*FetchPackagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchPackagesResponse)
	err := c.cc.Invoke(ctx, SearchService_FetchPackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) FetchPackageVersion(ctx context.Context, in *FetchPackageVersionRequest, opts ...grpc.CallOption) (*FetchPackageVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchPackageVersionResponse)
	err := c.cc.Invoke(ctx, SearchService_FetchPackageVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) FetchVulnerabilities(ctx context.Context, in *FetchVulnerabilitiesRequest, opts ...grpc.CallOption) (*FetchVulnerabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchVulnerabilitiesResponse)
	err := c.cc.Invoke(ctx, SearchService_FetchVulnerabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
// All implementations must embed UnimplementedSearchServiceServer
// for forward compatibility.
//
// SearchService defines the methods for searching packages
type SearchServiceServer interface {
	// ListPackages returns a list of packages available. Mostly meant for browsing if a package is available or not
	ListPackages(context.Context, *ListPackagesRequest) (*ListPackagesResponse, error)
	// FetchPackage returns a package based on the name
	FetchPackages(context.Context, *FetchPackagesRequest) (*FetchPackagesResponse, error)
	// FetchPackageVersion returns a package based on the name and version
	FetchPackageVersion(context.Context, *FetchPackageVersionRequest) (*FetchPackageVersionResponse, error)
	// FetchVulnerabilities returns a list of vulnerabilities for a package based on the name and version
	FetchVulnerabilities(context.Context, *FetchVulnerabilitiesRequest) (*FetchVulnerabilitiesResponse, error)
	mustEmbedUnimplementedSearchServiceServer()
}

// UnimplementedSearchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchServiceServer struct{}

func (UnimplementedSearchServiceServer) ListPackages(context.Context, *ListPackagesRequest) (*ListPackagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPackages not implemented")
}
func (UnimplementedSearchServiceServer) FetchPackages(context.Context, *FetchPackagesRequest) (*FetchPackagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchPackages not implemented")
}
func (UnimplementedSearchServiceServer) FetchPackageVersion(context.Context, *FetchPackageVersionRequest) (*FetchPackageVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchPackageVersion not implemented")
}
func (UnimplementedSearchServiceServer) FetchVulnerabilities(context.Context, *FetchVulnerabilitiesRequest) (*FetchVulnerabilitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchVulnerabilities not implemented")
}
func (UnimplementedSearchServiceServer) mustEmbedUnimplementedSearchServiceServer() {}
func (UnimplementedSearchServiceServer) testEmbeddedByValue()                       {}

// UnsafeSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServiceServer will
// result in compilation errors.
type UnsafeSearchServiceServer interface {
	mustEmbedUnimplementedSearchServiceServer()
}

func RegisterSearchServiceServer(s grpc.ServiceRegistrar, srv SearchServiceServer) {
	// If the following call pancis, it indicates UnimplementedSearchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SearchService_ServiceDesc, srv)
}

func _SearchService_ListPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPackagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).ListPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_ListPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).ListPackages(ctx, req.(*ListPackagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_FetchPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchPackagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).FetchPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_FetchPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).FetchPackages(ctx, req.(*FetchPackagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_FetchPackageVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchPackageVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).FetchPackageVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_FetchPackageVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).FetchPackageVersion(ctx, req.(*FetchPackageVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_FetchVulnerabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchVulnerabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).FetchVulnerabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_FetchVulnerabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).FetchVulnerabilities(ctx, req.(*FetchVulnerabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchService_ServiceDesc is the grpc.ServiceDesc for SearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "buildsafe.v1.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPackages",
			Handler:    _SearchService_ListPackages_Handler,
		},
		{
			MethodName: "FetchPackages",
			Handler:    _SearchService_FetchPackages_Handler,
		},
		{
			MethodName: "FetchPackageVersion",
			Handler:    _SearchService_FetchPackageVersion_Handler,
		},
		{
			MethodName: "FetchVulnerabilities",
			Handler:    _SearchService_FetchVulnerabilities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "buildsafe/v1/search.proto",
}
