// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: buildsafe/v1/search.proto

package bsfv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on FetchPackagesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FetchPackagesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FetchPackagesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FetchPackagesRequestMultiError, or nil if none found.
func (m *FetchPackagesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *FetchPackagesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return FetchPackagesRequestMultiError(errors)
	}

	return nil
}

// FetchPackagesRequestMultiError is an error wrapping multiple validation
// errors returned by FetchPackagesRequest.ValidateAll() if the designated
// constraints aren't met.
type FetchPackagesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FetchPackagesRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FetchPackagesRequestMultiError) AllErrors() []error { return m }

// FetchPackagesRequestValidationError is the validation error returned by
// FetchPackagesRequest.Validate if the designated constraints aren't met.
type FetchPackagesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FetchPackagesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FetchPackagesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FetchPackagesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FetchPackagesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FetchPackagesRequestValidationError) ErrorName() string {
	return "FetchPackagesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e FetchPackagesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFetchPackagesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FetchPackagesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FetchPackagesRequestValidationError{}

// Validate checks the field values on FetchPackagesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FetchPackagesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FetchPackagesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FetchPackagesResponseMultiError, or nil if none found.
func (m *FetchPackagesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *FetchPackagesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetPackages() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, FetchPackagesResponseValidationError{
						field:  fmt.Sprintf("Packages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, FetchPackagesResponseValidationError{
						field:  fmt.Sprintf("Packages[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return FetchPackagesResponseValidationError{
					field:  fmt.Sprintf("Packages[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return FetchPackagesResponseMultiError(errors)
	}

	return nil
}

// FetchPackagesResponseMultiError is an error wrapping multiple validation
// errors returned by FetchPackagesResponse.ValidateAll() if the designated
// constraints aren't met.
type FetchPackagesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FetchPackagesResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FetchPackagesResponseMultiError) AllErrors() []error { return m }

// FetchPackagesResponseValidationError is the validation error returned by
// FetchPackagesResponse.Validate if the designated constraints aren't met.
type FetchPackagesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FetchPackagesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FetchPackagesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FetchPackagesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FetchPackagesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FetchPackagesResponseValidationError) ErrorName() string {
	return "FetchPackagesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e FetchPackagesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFetchPackagesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FetchPackagesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FetchPackagesResponseValidationError{}

// Validate checks the field values on FetchMaintainersInfoRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FetchMaintainersInfoRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FetchMaintainersInfoRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FetchMaintainersInfoRequestMultiError, or nil if none found.
func (m *FetchMaintainersInfoRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *FetchMaintainersInfoRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Version

	if len(errors) > 0 {
		return FetchMaintainersInfoRequestMultiError(errors)
	}

	return nil
}

// FetchMaintainersInfoRequestMultiError is an error wrapping multiple
// validation errors returned by FetchMaintainersInfoRequest.ValidateAll() if
// the designated constraints aren't met.
type FetchMaintainersInfoRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FetchMaintainersInfoRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FetchMaintainersInfoRequestMultiError) AllErrors() []error { return m }

// FetchMaintainersInfoRequestValidationError is the validation error returned
// by FetchMaintainersInfoRequest.Validate if the designated constraints
// aren't met.
type FetchMaintainersInfoRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FetchMaintainersInfoRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FetchMaintainersInfoRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FetchMaintainersInfoRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FetchMaintainersInfoRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FetchMaintainersInfoRequestValidationError) ErrorName() string {
	return "FetchMaintainersInfoRequestValidationError"
}

// Error satisfies the builtin error interface
func (e FetchMaintainersInfoRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFetchMaintainersInfoRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FetchMaintainersInfoRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FetchMaintainersInfoRequestValidationError{}

// Validate checks the field values on ListPackagesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListPackagesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListPackagesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListPackagesRequestMultiError, or nil if none found.
func (m *ListPackagesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListPackagesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PageSize

	// no validation rules for PageToken

	// no validation rules for SearchTerm

	if len(errors) > 0 {
		return ListPackagesRequestMultiError(errors)
	}

	return nil
}

// ListPackagesRequestMultiError is an error wrapping multiple validation
// errors returned by ListPackagesRequest.ValidateAll() if the designated
// constraints aren't met.
type ListPackagesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListPackagesRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListPackagesRequestMultiError) AllErrors() []error { return m }

// ListPackagesRequestValidationError is the validation error returned by
// ListPackagesRequest.Validate if the designated constraints aren't met.
type ListPackagesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPackagesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPackagesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPackagesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPackagesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPackagesRequestValidationError) ErrorName() string {
	return "ListPackagesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListPackagesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPackagesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPackagesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPackagesRequestValidationError{}

// Validate checks the field values on ListPackagesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListPackagesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListPackagesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListPackagesResponseMultiError, or nil if none found.
func (m *ListPackagesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListPackagesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for NextPageToken

	// no validation rules for TotalPages

	if len(errors) > 0 {
		return ListPackagesResponseMultiError(errors)
	}

	return nil
}

// ListPackagesResponseMultiError is an error wrapping multiple validation
// errors returned by ListPackagesResponse.ValidateAll() if the designated
// constraints aren't met.
type ListPackagesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListPackagesResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListPackagesResponseMultiError) AllErrors() []error { return m }

// ListPackagesResponseValidationError is the validation error returned by
// ListPackagesResponse.Validate if the designated constraints aren't met.
type ListPackagesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPackagesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPackagesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPackagesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPackagesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPackagesResponseValidationError) ErrorName() string {
	return "ListPackagesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListPackagesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPackagesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPackagesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPackagesResponseValidationError{}

// Validate checks the field values on Package with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Package) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Package with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in PackageMultiError, or nil if none found.
func (m *Package) ValidateAll() error {
	return m.validate(true)
}

func (m *Package) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Revision

	// no validation rules for Version

	// no validation rules for Description

	// no validation rules for Homepage

	// no validation rules for Free

	// no validation rules for SpdxId

	// no validation rules for EpochSeconds

	// no validation rules for Cpe

	// no validation rules for AttrName

	// no validation rules for MaintainerName

	if len(errors) > 0 {
		return PackageMultiError(errors)
	}

	return nil
}

// PackageMultiError is an error wrapping multiple validation errors returned
// by Package.ValidateAll() if the designated constraints aren't met.
type PackageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PackageMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PackageMultiError) AllErrors() []error { return m }

// PackageValidationError is the validation error returned by Package.Validate
// if the designated constraints aren't met.
type PackageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PackageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PackageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PackageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PackageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PackageValidationError) ErrorName() string { return "PackageValidationError" }

// Error satisfies the builtin error interface
func (e PackageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPackage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PackageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PackageValidationError{}

// Validate checks the field values on Maintainer with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Maintainer) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Maintainer with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MaintainerMultiError, or
// nil if none found.
func (m *Maintainer) ValidateAll() error {
	return m.validate(true)
}

func (m *Maintainer) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Email

	// no validation rules for Github

	// no validation rules for GithubId

	// no validation rules for Name

	if len(errors) > 0 {
		return MaintainerMultiError(errors)
	}

	return nil
}

// MaintainerMultiError is an error wrapping multiple validation errors
// returned by Maintainer.ValidateAll() if the designated constraints aren't met.
type MaintainerMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MaintainerMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MaintainerMultiError) AllErrors() []error { return m }

// MaintainerValidationError is the validation error returned by
// Maintainer.Validate if the designated constraints aren't met.
type MaintainerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MaintainerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MaintainerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MaintainerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MaintainerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MaintainerValidationError) ErrorName() string { return "MaintainerValidationError" }

// Error satisfies the builtin error interface
func (e MaintainerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMaintainer.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MaintainerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MaintainerValidationError{}

// Validate checks the field values on FetchPackageVersionRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FetchPackageVersionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FetchPackageVersionRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FetchPackageVersionRequestMultiError, or nil if none found.
func (m *FetchPackageVersionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *FetchPackageVersionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Version

	if len(errors) > 0 {
		return FetchPackageVersionRequestMultiError(errors)
	}

	return nil
}

// FetchPackageVersionRequestMultiError is an error wrapping multiple
// validation errors returned by FetchPackageVersionRequest.ValidateAll() if
// the designated constraints aren't met.
type FetchPackageVersionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FetchPackageVersionRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FetchPackageVersionRequestMultiError) AllErrors() []error { return m }

// FetchPackageVersionRequestValidationError is the validation error returned
// by FetchPackageVersionRequest.Validate if the designated constraints aren't met.
type FetchPackageVersionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FetchPackageVersionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FetchPackageVersionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FetchPackageVersionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FetchPackageVersionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FetchPackageVersionRequestValidationError) ErrorName() string {
	return "FetchPackageVersionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e FetchPackageVersionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFetchPackageVersionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FetchPackageVersionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FetchPackageVersionRequestValidationError{}

// Validate checks the field values on FetchPackageVersionResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FetchPackageVersionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FetchPackageVersionResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FetchPackageVersionResponseMultiError, or nil if none found.
func (m *FetchPackageVersionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *FetchPackageVersionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPackage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, FetchPackageVersionResponseValidationError{
					field:  "Package",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, FetchPackageVersionResponseValidationError{
					field:  "Package",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPackage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FetchPackageVersionResponseValidationError{
				field:  "Package",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return FetchPackageVersionResponseMultiError(errors)
	}

	return nil
}

// FetchPackageVersionResponseMultiError is an error wrapping multiple
// validation errors returned by FetchPackageVersionResponse.ValidateAll() if
// the designated constraints aren't met.
type FetchPackageVersionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FetchPackageVersionResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FetchPackageVersionResponseMultiError) AllErrors() []error { return m }

// FetchPackageVersionResponseValidationError is the validation error returned
// by FetchPackageVersionResponse.Validate if the designated constraints
// aren't met.
type FetchPackageVersionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FetchPackageVersionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FetchPackageVersionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FetchPackageVersionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FetchPackageVersionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FetchPackageVersionResponseValidationError) ErrorName() string {
	return "FetchPackageVersionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e FetchPackageVersionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFetchPackageVersionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FetchPackageVersionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FetchPackageVersionResponseValidationError{}

// Validate checks the field values on FetchVulnerabilitiesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FetchVulnerabilitiesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FetchVulnerabilitiesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FetchVulnerabilitiesRequestMultiError, or nil if none found.
func (m *FetchVulnerabilitiesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *FetchVulnerabilitiesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Version

	if len(errors) > 0 {
		return FetchVulnerabilitiesRequestMultiError(errors)
	}

	return nil
}

// FetchVulnerabilitiesRequestMultiError is an error wrapping multiple
// validation errors returned by FetchVulnerabilitiesRequest.ValidateAll() if
// the designated constraints aren't met.
type FetchVulnerabilitiesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FetchVulnerabilitiesRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FetchVulnerabilitiesRequestMultiError) AllErrors() []error { return m }

// FetchVulnerabilitiesRequestValidationError is the validation error returned
// by FetchVulnerabilitiesRequest.Validate if the designated constraints
// aren't met.
type FetchVulnerabilitiesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FetchVulnerabilitiesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FetchVulnerabilitiesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FetchVulnerabilitiesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FetchVulnerabilitiesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FetchVulnerabilitiesRequestValidationError) ErrorName() string {
	return "FetchVulnerabilitiesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e FetchVulnerabilitiesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFetchVulnerabilitiesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FetchVulnerabilitiesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FetchVulnerabilitiesRequestValidationError{}

// Validate checks the field values on FetchVulnerabilitiesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FetchVulnerabilitiesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FetchVulnerabilitiesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FetchVulnerabilitiesResponseMultiError, or nil if none found.
func (m *FetchVulnerabilitiesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *FetchVulnerabilitiesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetVulnerabilities() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, FetchVulnerabilitiesResponseValidationError{
						field:  fmt.Sprintf("Vulnerabilities[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, FetchVulnerabilitiesResponseValidationError{
						field:  fmt.Sprintf("Vulnerabilities[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return FetchVulnerabilitiesResponseValidationError{
					field:  fmt.Sprintf("Vulnerabilities[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return FetchVulnerabilitiesResponseMultiError(errors)
	}

	return nil
}

// FetchVulnerabilitiesResponseMultiError is an error wrapping multiple
// validation errors returned by FetchVulnerabilitiesResponse.ValidateAll() if
// the designated constraints aren't met.
type FetchVulnerabilitiesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FetchVulnerabilitiesResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FetchVulnerabilitiesResponseMultiError) AllErrors() []error { return m }

// FetchVulnerabilitiesResponseValidationError is the validation error returned
// by FetchVulnerabilitiesResponse.Validate if the designated constraints
// aren't met.
type FetchVulnerabilitiesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FetchVulnerabilitiesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FetchVulnerabilitiesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FetchVulnerabilitiesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FetchVulnerabilitiesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FetchVulnerabilitiesResponseValidationError) ErrorName() string {
	return "FetchVulnerabilitiesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e FetchVulnerabilitiesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFetchVulnerabilitiesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FetchVulnerabilitiesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FetchVulnerabilitiesResponseValidationError{}

// Validate checks the field values on Vulnerability with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Vulnerability) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Vulnerability with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in VulnerabilityMultiError, or
// nil if none found.
func (m *Vulnerability) ValidateAll() error {
	return m.validate(true)
}

func (m *Vulnerability) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Severity

	for idx, item := range m.GetCvss() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, VulnerabilityValidationError{
						field:  fmt.Sprintf("Cvss[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, VulnerabilityValidationError{
						field:  fmt.Sprintf("Cvss[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return VulnerabilityValidationError{
					field:  fmt.Sprintf("Cvss[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return VulnerabilityMultiError(errors)
	}

	return nil
}

// VulnerabilityMultiError is an error wrapping multiple validation errors
// returned by Vulnerability.ValidateAll() if the designated constraints
// aren't met.
type VulnerabilityMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VulnerabilityMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VulnerabilityMultiError) AllErrors() []error { return m }

// VulnerabilityValidationError is the validation error returned by
// Vulnerability.Validate if the designated constraints aren't met.
type VulnerabilityValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VulnerabilityValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VulnerabilityValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VulnerabilityValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VulnerabilityValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VulnerabilityValidationError) ErrorName() string { return "VulnerabilityValidationError" }

// Error satisfies the builtin error interface
func (e VulnerabilityValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVulnerability.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VulnerabilityValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VulnerabilityValidationError{}

// Validate checks the field values on Cvss with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Cvss) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Cvss with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in CvssMultiError, or nil if none found.
func (m *Cvss) ValidateAll() error {
	return m.validate(true)
}

func (m *Cvss) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Vector

	// no validation rules for Version

	// no validation rules for Source

	// no validation rules for Type

	if all {
		switch v := interface{}(m.GetMetrics()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CvssValidationError{
					field:  "Metrics",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CvssValidationError{
					field:  "Metrics",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMetrics()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CvssValidationError{
				field:  "Metrics",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CvssMultiError(errors)
	}

	return nil
}

// CvssMultiError is an error wrapping multiple validation errors returned by
// Cvss.ValidateAll() if the designated constraints aren't met.
type CvssMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CvssMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CvssMultiError) AllErrors() []error { return m }

// CvssValidationError is the validation error returned by Cvss.Validate if the
// designated constraints aren't met.
type CvssValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CvssValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CvssValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CvssValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CvssValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CvssValidationError) ErrorName() string { return "CvssValidationError" }

// Error satisfies the builtin error interface
func (e CvssValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCvss.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CvssValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CvssValidationError{}

// Validate checks the field values on Cvss3Metrics with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Cvss3Metrics) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Cvss3Metrics with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in Cvss3MetricsMultiError, or
// nil if none found.
func (m *Cvss3Metrics) ValidateAll() error {
	return m.validate(true)
}

func (m *Cvss3Metrics) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BaseScore

	// no validation rules for ExploitabilityScore

	// no validation rules for ImpactScore

	if len(errors) > 0 {
		return Cvss3MetricsMultiError(errors)
	}

	return nil
}

// Cvss3MetricsMultiError is an error wrapping multiple validation errors
// returned by Cvss3Metrics.ValidateAll() if the designated constraints aren't met.
type Cvss3MetricsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Cvss3MetricsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Cvss3MetricsMultiError) AllErrors() []error { return m }

// Cvss3MetricsValidationError is the validation error returned by
// Cvss3Metrics.Validate if the designated constraints aren't met.
type Cvss3MetricsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Cvss3MetricsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Cvss3MetricsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Cvss3MetricsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Cvss3MetricsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Cvss3MetricsValidationError) ErrorName() string { return "Cvss3MetricsValidationError" }

// Error satisfies the builtin error interface
func (e Cvss3MetricsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCvss3Metrics.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Cvss3MetricsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Cvss3MetricsValidationError{}
